version: '3.8'

services:
  app:
    build:
      context: ./app/
      args:
        BUILD_MODE: ${BUILD_MODE}
    volumes:
      - ../:/var/www/html
    links:
      - db
      - redis
    ports:
      - ${SERVER_PORT}:8000
    restart: unless-stopped

  queue:
    build:
      context: ./queue/
      args:
        BUILD_MODE: ${BUILD_MODE}
    volumes:
      - ../:/var/www/html
    links:
      - db
      - redis

  schedule:
    build:
      context: ./schedule/
      args:
        BUILD_MODE: ${BUILD_MODE}
    volumes:
      - ../:/var/www/html
    links:
      - db
      - redis

  db:
    build:
      context: ./db/
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/dumps/:/tmp
    ports:
      - "5432:5432"

  redis:
    build:
      context: ./redis/
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  db_manager:
    build:
      context: ./db_manager/
    ports:
      - ${DB_MANAGER_PORT}:8080

volumes:
  redis:
    driver: local
